site_name: Fastapi Handbook
theme:
  name: material
  features:
  - navigation.tabs
  - navigation.tabs.sticky

nav:
- Home: ./index.md
- Dependency Injection:
  - Introduction: ./dependency-injection/introduction.md
  - FastAPI Injection: ./dependency-injection/fastapi-injection.md
  - Advanced:
    - Design Patterns: ./dependency-injection/design-patterns.md
    - Testing: ./dependency-injection/testing.md
    - Performance: ./dependency-injection/performance.md
  - Case Studies:
    - Authentication: ./dependency-injection/auth.md
    - Database Management: ./dependency-injection/database.md
    - External Services: ./dependency-injection/external-services.md
  - Best Practice: ./dependency-injection/best-practice.md

- OpenAPI:
  - Introduction: ./openapi/introduction.md
  - Basic Usage: ./openapi/basic-usage.md
  - Pydantic Models: ./openapi/pydantic-models.md
  - OpenAPI Schema: ./openapi/openapi-schema.md
  - Advanced: ./openapi/advanced-schema.md
  - API documentation: ./openapi/api-documentation.md
  - Best Practice: ./openapi/best-practice.md
  - Troubleshooting: ./openapi/troubleshooting.md

- Middleware:
  - Basic: ./middleware/introduction.md
  - Implementation: ./middleware/implementation.md
  - Use Cases: ./middleware/use-cases.md
  - Advanced: ./middleware/advanced.md
  - Best Practice: ./middleware/best-practice.md

- Error Handling:
  - Basic: ./error-handling/basic.md
  - Built-in Exceptions: ./error-handling/built-in-exceptions.md
  - Custom Exceptions: ./error-handling/custom-exceptions.md
  - Global Error Handling: ./error-handling/global-error-handling.md
  - API Routing: ./error-handling/api-routing.md
  - Best Practice: ./error-handling/best-practice.md

- Testing:
  - Basic: ./testing/introduction.md
  - Unit Testing: ./testing/unit-testing.md
  - Integration Testing: ./testing/integration-testing.md
  - Database Testing: ./testing/database-testing.md
  - Asynchronous Testing: ./testing/asynchronous-testing.md
  - Mocking: ./testing/mocking.md
  - Best Practice: ./testing/best-practice.md
